[package]

name = "dotenv"
version = "0.3.0"
authors = [
	"Santiago Lapresta <santiago.lapresta@gmail.com>",
	"Craig Hills <chills@gmail.com>",
	"Mike Piccolo <mfpiccolo@gmail.com>",
]
readme = "README.md"
keywords = ["environment", "env", "dotenv", "settings", "config"]
license = "MIT"
homepage = "https://github.com/slapresta/rust-dotenv"
repository = "https://github.com/slapresta/rust-dotenv"
description = "A `dotenv` implementation for Rust"

[dependencies]
regex = "*"
