name: Publish

on:
    push:
        branches:
            -   main
    pull_request:
        branches:
            -   master
    workflow_dispatch:

jobs:
    publish:
        name: Publish
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout sources
                uses: actions/checkout@v2

            -   name: Install stable toolchain
                uses: actions-rs/toolchain@v1
                with:
                    profile: minimal
                    toolchain: stable
                    override: true

            -   name: Publish dotenvx
                run: cargo publish --token ${CRATES_TOKEN} -p dotenvx
                env:
                    CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}

            -   name: Publish dotenvx_codegen_implementation
                run: cargo publish --token ${CRATES_TOKEN} -p dotenvx_codegen_implementation
                env:
                    CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}

            -   name: Publish dotenvx_codegen
                run: cargo publish --token ${CRATES_TOKEN} -p dotenvx_codegen
                env:
                    CRATES_TOKEN: ${{ secrets.CRATES_TOKEN }}
